services:
  app:
    build: .
    container_name: rails-react-app
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - rails-db:/app/db
    environment:
      RAILS_ENV: development
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite-db
    volumes:
      - rails-db:/root/db

volumes:
  rails-db: